-- Kokoroe V1: 底片卷期主表
--
-- 設計說明：
--  * format / status 存字串而非數字。搭配 JPA 的 @Enumerated(EnumType.STRING)，
--    日後在 enum 中間插入新值時不會讓既有資料語意錯位。
--  * 三條 CHECK 約束是「最後一道防線」。應用層已用 Bean Validation 擋過一次，
--    但資料庫層的約束能防住繞過 API 的直接寫入（手動 SQL、未來的批次匯入）。

CREATE TABLE film_roll (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name       VARCHAR(100) NOT NULL,
    brand           VARCHAR(50),
    iso             INTEGER      NOT NULL,
    format          VARCHAR(16)  NOT NULL,
    push_pull_stops INTEGER      NOT NULL DEFAULT 0,
    loaded_at       DATE         NOT NULL,
    finished_at     DATE,
    camera_name     VARCHAR(100),
    lens_name       VARCHAR(100),
    notes           TEXT,
    status          VARCHAR(16)  NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT ck_film_roll_iso       CHECK (iso > 0 AND iso <= 12800),
    CONSTRAINT ck_film_roll_push_pull CHECK (push_pull_stops BETWEEN -3 AND 3),
    CONSTRAINT ck_film_roll_dates     CHECK (finished_at IS NULL OR finished_at >= loaded_at)
);

-- 列表頁的主要查詢型態：依狀態篩選、依裝片日期新到舊排序。
CREATE INDEX idx_film_roll_status    ON film_roll (status);
CREATE INDEX idx_film_roll_loaded_at ON film_roll (loaded_at DESC);
