-- Kokoroe V2: 拆出相機實體，並把 film_roll.camera_name 的既有字串搬進來
--
-- 設計說明：
--  * 規格欄位（機型、對焦、過片、閃光燈…）全部可為 NULL，NULL 代表「還不知道」。
--    從舊字串搬過來的相機只知道名稱與片幅，其餘要使用者事後補。
--  * enum 欄位加 CHECK：手動 SQL 寫成 '135' 而不是 'FORMAT_135' 時，
--    在寫入當下就失敗，而不是等到讀取時才讓 API 回 500。
--  * 唯一索引用 lower() + coalesce()：'PENTAX PG-50' 與 'Pentax pg-50' 視為同一台，
--    沒有品牌的相機也不會因為 NULL <> NULL 而逃過唯一性檢查。
--  * film_roll.camera_name 這次先保留，確認資料搬遷無誤後，由下一支 migration 移除。

CREATE TABLE camera (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand                VARCHAR(50),
    model                VARCHAR(100) NOT NULL,
    format               VARCHAR(16)  NOT NULL,
    camera_type          VARCHAR(20),
    focus_type           VARCHAR(16),
    film_advance         VARCHAR(16),
    has_flash            BOOLEAN,
    interchangeable_lens BOOLEAN,
    fixed_lens           VARCHAR(100),
    shutter_speed_range  VARCHAR(50),
    iso_min              INTEGER,
    iso_max              INTEGER,
    notes                TEXT,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT ck_camera_format       CHECK (format IN ('FORMAT_135', 'FORMAT_120', 'HALF_FRAME')),
    CONSTRAINT ck_camera_type         CHECK (camera_type IN ('POINT_AND_SHOOT', 'SLR', 'RANGEFINDER', 'TLR', 'DISPOSABLE', 'OTHER')),
    CONSTRAINT ck_camera_focus_type   CHECK (focus_type IN ('AUTO', 'MANUAL', 'FIXED', 'ZONE')),
    CONSTRAINT ck_camera_film_advance CHECK (film_advance IN ('MANUAL', 'AUTO')),
    -- 可換鏡頭的機身不會有「內建定焦鏡頭」
    CONSTRAINT ck_camera_fixed_lens   CHECK (NOT (interchangeable_lens IS TRUE AND fixed_lens IS NOT NULL)),
    CONSTRAINT ck_camera_iso_range    CHECK (
        (iso_min IS NULL OR iso_min BETWEEN 1 AND 12800)
        AND (iso_max IS NULL OR iso_max BETWEEN 1 AND 12800)
        AND (iso_min IS NULL OR iso_max IS NULL OR iso_min <= iso_max)
    )
);

CREATE UNIQUE INDEX uq_camera_brand_model ON camera (lower(coalesce(brand, '')), lower(model));

-- 預設的 NO ACTION：還有卷期使用中的相機不能被刪除（應用層會先擋並回 409）。
ALTER TABLE film_roll ADD COLUMN camera_id BIGINT REFERENCES camera (id);
CREATE INDEX idx_film_roll_camera_id ON film_roll (camera_id);

-- ---------------------------------------------------------------------------
-- 資料搬遷
-- ---------------------------------------------------------------------------
-- 1. 正規化名稱：連續空白壓成一個、去頭尾空白；空字串視同沒填。
-- 2. 不分大小寫分組；同組裡出現最多次的寫法當作顯示名稱，
--    片幅取這台相機拍過最多次的底片規格（FORMAT_135 / FORMAT_120 與相機的值同名）。
-- 3. 第一個空白前當品牌、之後當型號（'PENTAX PG-50' → 'PENTAX' + 'PG-50'）。
--    沒有空白、或第一個字超過品牌欄位長度時，整串當型號，品牌留空。
-- 4. 回填 camera_id 時只連「底片規格與相機片幅相同」的卷期。
--    舊資料可能把同一個名稱同時用在 135 和 120（打錯字或同名不同機），
--    少數那一邊若也連上，會違反應用層的相容規則，之後連推進狀態都會被擋下。
--    沒連上的卷期保留 camera_name，camera_id 維持 NULL，由使用者自行指定相機。
WITH normalized AS (
    SELECT btrim(regexp_replace(camera_name, '\s+', ' ', 'g')) AS name, format
    FROM film_roll
    WHERE camera_name IS NOT NULL
), grouped AS (
    SELECT mode() WITHIN GROUP (ORDER BY name)   AS name,
           mode() WITHIN GROUP (ORDER BY format) AS format
    FROM normalized
    WHERE name <> ''
    GROUP BY lower(name)
), split AS (
    SELECT name, format, position(' ' IN name) AS sp
    FROM grouped
)
INSERT INTO camera (brand, model, format, created_at, updated_at)
SELECT CASE WHEN sp BETWEEN 2 AND 51 THEN left(name, sp - 1) END,
       CASE WHEN sp BETWEEN 2 AND 51 THEN substr(name, sp + 1) ELSE name END,
       format,
       now(),
       now()
FROM split;

UPDATE film_roll fr
SET camera_id = c.id
FROM camera c
WHERE lower(btrim(regexp_replace(fr.camera_name, '\s+', ' ', 'g'))) = lower(concat_ws(' ', c.brand, c.model))
  -- 這裡建立的相機片幅只會是 FORMAT_135 / FORMAT_120，與卷期的值同名，直接比對即可
  AND c.format = fr.format;
