-- Kokoroe V4: 卷期照片
--
-- 設計說明：
--  * 圖檔本身放在物件儲存（本機 RustFS、正式環境 Cloudflare R2），資料庫只存中繼資料。
--    storage_key 是這張照片在儲存空間裡的前綴，底下固定有 original.jpg / web.jpg / thumb.jpg 三個版本。
--  * width / height 是「依 EXIF 轉正之後」的原圖尺寸，前端排版用它算長寬比，載入前就能先佔好位置。
--  * frame_number 是底片上的格號。0 到 99 涵蓋 135（含 00、0 格）、120 與半格機。
--    同一卷同一格只能有一張；重掃要先刪掉舊的。
--  * 刪除卷期時，資料庫用 ON DELETE CASCADE 一起刪掉照片紀錄當最後防線；
--    儲存空間的圖檔由應用層在交易提交後清掉（資料庫碰不到物件儲存）。

CREATE TABLE photo (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_roll_id      BIGINT       NOT NULL REFERENCES film_roll (id) ON DELETE CASCADE,
    frame_number      INTEGER      NOT NULL,
    storage_key       VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255),
    width             INTEGER      NOT NULL,
    height            INTEGER      NOT NULL,
    size_bytes        BIGINT       NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT ck_photo_frame_number CHECK (frame_number BETWEEN 0 AND 99),
    CONSTRAINT ck_photo_dimensions   CHECK (width > 0 AND height > 0),
    CONSTRAINT ck_photo_size_bytes   CHECK (size_bytes > 0),
    -- 也兼作「依卷期查照片」的索引：film_roll_id 是第一個欄位
    CONSTRAINT uq_photo_roll_frame   UNIQUE (film_roll_id, frame_number),
    CONSTRAINT uq_photo_storage_key  UNIQUE (storage_key)
);
